name: "CI - Primeira integração"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  exemplo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Rodar um hello world
        run: echo Hello, World

      - name: Listar os arquivos
        run: ls -la

      - name: Mostrar o arquivo empregado
        run: cat src/main/java/com/caio/ci_lab/application/core/domain/Empregado.java

      - name: Ver o Java do runner
        run: java -version